# Pre-commit git hooks.
#
# Usage:
#   1. Run one of:
#     $ pip install pre-commit
#     $ brew install pre-commit
#
#   2. Install hooks
#     $ pre-commit install
#
#   3. Optionally, enable automatic updates
#     $ pre-commit autoupdate
repos:
- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
  - id: black
    name: black
    entry: black
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    name: isort
    args: [--force-single-line-imports]
- repo: local
  hooks:
  - id: composer-validate
    name: composer-validate
    language: script
    entry: scripts/pre-commit.sh
    files: 'composer\.json'
    pass_filenames: true
- repo: https://github.com/jazzband/pip-tools
  rev: 7.3.0
  hooks:
  - id: pip-compile
    name: pip-compile scripts/make_release_requirements.in
    files: ^(.*/)?make_release_requirements\.(in|txt)$
    args: [--output-file=scripts/make_release_requirements.txt, scripts/make_release_requirements.in]
