name: Black code formatter

on:
  pull_request:

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install black
        run: pip install black

      - name: Get changed python files
        id: changed-files
        uses: tj-actions/changed-files@v37
        with:
          files: "**/*.py"

      - name: Check changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: black --check --color --diff --quiet ${{ steps.changed-files.outputs.all_changed_files }}
