name: Update Changelog

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  release:
    # Prevent this workflow from running elsewhere.
    if: github.repository_owner == 'php-curl-class'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install --requirement scripts/requirements.txt

      - name: Set git details
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Update list
        run: python scripts/update_changelog.py
        env:
          PRODUCTION: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
